// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/protobuf/greet.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class Greeting;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - GreetRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface GreetRoot : GPBRootObject
@end

#pragma mark - Greeting

typedef GPB_ENUM(Greeting_FieldNumber) {
  Greeting_FieldNumber_FirstName = 1,
  Greeting_FieldNumber_LastName = 2,
};

@interface Greeting : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *firstName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *lastName;

@end

#pragma mark - GreetRequest

typedef GPB_ENUM(GreetRequest_FieldNumber) {
  GreetRequest_FieldNumber_Greeting = 1,
};

@interface GreetRequest : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) Greeting *greeting;
/** Test to see if @c greeting has been set. */
@property(nonatomic, readwrite) BOOL hasGreeting;

@end

#pragma mark - GreetResponse

typedef GPB_ENUM(GreetResponse_FieldNumber) {
  GreetResponse_FieldNumber_Result = 1,
};

@interface GreetResponse : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *result;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
